<div class="footer">
	<div class='container'>
		<div class="row">
			<div class="col-sm-2" style="margin-right:70px;">
				<ul>
					<li class="title">行业与解决方案</li>
					<li class='yi'>
						<a href="/cn/zh/dealers.html">汽车</a>
						<ul>
							<li class='er'><a href="/cn/zh/automaker.html">主机厂</a></li>
							<li class='er'><a href="/cn/zh/dealers.html">经销商</a></li>
						</ul>
					</li>
					<li class='yi'><a href="/cn/zh/real-estate.html">地产</a></li>
					<li class='yi'><a href="/cn/zh/new-retail.html">新零售</a></li>
				</ul>
			</div>
			<div class="col-sm-2">
				<ul style="position:relative;">
					<li class="title">咨询规划</li>
					<li class='yi'>
						<a href="/cn/en/strategy-transformation.html">创新变革</a>
						<ul>
							<li class='er'><a href="/cn/en/strategy-transformation.html">新零售</a></li>
							<li class='er'><a href="/cn/en/strategy-transformation.html">数字化经营</a></li>
						</ul>
					</li>
					<li class='yi'>
						<a href="/cn/en/business-management.html">企业运营</a>
						<ul>
							<li class='er'><a href="/cn/en/business-management.html">业务财务一体化</a></li>
							<li class='er'><a href="/cn/en/business-management.html">全面预算管理</a></li>
							<li class='er'><a href="/cn/en/business-management.html">企业综合绩效管理模型</a></li>
						</ul>
					</li>
					<li class='yi'>
						<a href="/cn/en/it-strategic-planning.html">IT&nbsp;咨询规划</a>
						<ul>
							<li class='er'><a href="/cn/en/it-strategic-planning.html">企业经营战略分解及IT支撑规划</a></li>
							<li class='er'><a href="/cn/en/it-strategic-planning.html">IT&nbsp;管控与组织设计</a></li>
							<li class='er'><a href="/cn/en/it-strategic-planning.html">项目管理及运维协同体系</a></li>
							<li class='er'><a href="/cn/en/it-strategic-planning.html">风险控制及价值评估 </a></li>
							<!--<li class='er'><a href="/pc/ruiy/itconsult/">项目管理及运维协同体系 
							（PMP 	&amp; ITIL）</a></li>-->
							<!-- <li class='er ch'><a href="/pc/ruiy/itconsult/">项目管理及运维协同体系 
							（PMP 	&amp; ITIL）</a></li> -->
						</ul>
					</li>
				</ul>
			</div>
			<div class="col-sm-2">
				<ul>
					<li class="title">软件实施</li>
					<li class='yi'>
						<a href="/cn/zh/salesforce.html">Salesforce</a>
						<ul>
							<li class='er'><a href="/cn/zh/salesforce.html">Sales Cloud</a></li>
							<li class='er'><a href="/cn/zh/salesforce.html">Service Cloud</a></li>
							<li class='er'><a href="/cn/zh/salesforce.html">Pardot</a></li>
							<li class='er'><a href="/cn/zh/salesforce.html">Community Cloud</a></li>
							
						</ul>
					</li>
					<li class='yi'>
						<a href="/cn/zh/sap.html">SAP</a>
						<ul>
							<li class='er'><a href="/cn/zh/sap.html">Hybris Marketing</a></li>
							<li class='er'><a href="/cn/zh/sap.html">Hybris Ecommence</a></li>
							<li class='er'><a href="/cn/zh/sap.html">Hybris C4C</a></li>
							<li class='er'><a href="/cn/zh/sap.html">DBM</a></li>
							<li class='er'><a href="/cn/zh/sap.html">S4</a></li>
							<li class='er'><a href="/cn/zh/sap.html">HANA</a></li>
							<li class='er'><a href="/cn/zh/sap.html">BPC</a></li>
						</ul>
					</li>
				</ul>
			</div>
			<div class="col-sm-2" style="margin-right:20px;">
				<ul style="height: 455px;">
					<li class="title">关于我们</li>
					<li class='yi'><a href="/cn/zh/breakingpoint-consulting.html">睿远咨询</a></li>
					<li class='yi'><a href="/cn/zh/contact-us.html">联系我们</a></li>
					<li class='yi'><a href="https://www.liepin.com/zhaopin/?sfrom=click-pc_homepage-centre_searchbox-search_new&d_sfrom=search_fp&key=%E7%9D%BF%E4%BB%AA" target="_blank">加入睿远</a></li>
					<li class='yi'><a href="/cn/zh/news-room.html">新闻室</a></li>
					<li class='yi'><a href="http://ibreakingpoint.huodongxing.com " target="_blank">活动沙龙</a></li>
					<li style="position: absolute;bottom:0px;"><img id='erw' style='width:150px;opacity:0;' src="/ruiy/images/er.jpg"></li>
				</ul>
			</div>
			<div class="col-sm-3">
				<ul style="height:455px;">
					<li class="title">合作伙伴</li>
					<li class='img' style="margin-left:20px;margin-top: 50px;"><a href="https://www.salesforce.com/cn/ " target="_blank"><img  style="width:70px;" src="/ruiy/images/yun.jpg"></a></li>
					<li class='img' style="margin-left:20px;"><a href="https://www.sap.com/china/index.html?campaigncode=CRM-CN17-PPC-BRDBZFC&source=PPC-CN-Baidu_BrandZone-BZ-TITLE " target="_blank"><img style="width:70px;margin-top: 5px;" src="/ruiy/images/sap.jpg"></a></li>
					<div style="position: absolute;bottom: 0px;">
						<li class='xtub'>
							<a target="_blank" href="https://www.facebook.com/ibreakingpoint"><img src="/ruiy/images/t1.jpg"></a>
							<a target="_blank" href="http://www.linkedin.com/groups?gid=3291404" ><img src="/ruiy/images/t2.jpg"></a>
							<a id='er' href="javascript:;"><img src="/ruiy/images/t3.png"></a>
						</li>
						<li class='yi' style='color:#fff;font-size:16px;margin-top:10px;'>客服咨询：400-820-7332</li>
						<li class='yi' style='color:#fff;font-size:16px;margin-top:10px;'>市场合作：021-34010561</li>
					</div>
				</ul>
			</div>

		</div>
	</div>
	<div class="col-sm-12 foot">&copy; 2018 ibreakingpoint.com &nbsp; 上海睿远软件信息咨询有限公司 &nbsp; 版权所有 沪ICP备11045576号-1&nbsp;&nbsp;
	<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1272959461'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1272959461%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script></div>
</div>
<script type="text/javascript" src='/ruiy/js/jquery-2.1.1.min.js'></script>
<script type="text/javascript">
	$('#er').mouseenter(function(){
		$('#erw').css('opacity',1);
	})
	$('#er').mouseleave(function(){
		$('#erw').css('opacity',0);
	})

</script>
