<?php 
  //详情页接口
  $id='355';
  $detail=fetch_json_data("/ServerZX/GetDetailById.cwg?id=".$id);
  
  $site=Cms_Service_Api_Website::getInstance()->getInfo();
?>

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><?php echo $meta->title; ?></title>
    <meta name="description" content="<?php echo $meta->description; ?>" />
    <meta name="keywords" content="<?php echo $meta->keywords; ?>" />
    <link rel="shortcut icon" href="<?php echo $meta->favicon; ?>" />
    <link rel="bookmark" href="<?php echo $meta->favicon; ?>" type="image/x-icon"　/>
    <link rel="icon" href="<?php echo $meta->favgif; ?>" type="image/gif" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=0" />
    <meta name="baidu-site-verification" content="ISvznniG2q" />
    <meta name="baidu-site-verification" content="l9jDiF4kqd" />
	<meta name="baidu-site-verification" content="qvC3nD7GAI" />
	<link rel="stylesheet" type="text/css" href="/ruiy/css/style.css">
	<link rel="stylesheet" type="text/css" href="/ruiy/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/ruiy/css/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="/ruiy/css/img-change.css">
</head>
<body>
<header id="header"><?php require __DIR__.'/../ruiy/header.phtml';?></header>
<!-- banner -->
<div class="banner">
	<div id="myCarousel1" class="carousel slide">
	    <?php Cms_Widget::factory('Ad')->display(Cms_Service_Api_Contents_Banner::getInstance()->getListByTypeId(100104),['need_LR'=>true,]); ?>
    </div>
</div>
<!-- nav -->
<div id="nav" class="navr">
	<ul style='margin: 0;'>
		<li><a href="/cn/zh/management-consulting.html">概述</a><span class="xian">|</span></li>
		<li><a href="/cn/zh/strategy-transformation.html">创新变革</a><span class="xian">|</span></li>
		<li><a href="/cn/zh/business-management.html">企业运营</a><span class="xian">|</span></li>
		<li><a class='active' href="/cn/zh/it-strategic-planning.html">IT咨询规划</a></li>
	</ul>
</div>
<!-- content -->
<div class='content'>
	<div class="container">
		<div class="row">
			<div class="col-sm-10 itconsult">
				<div class="row">
					<div class="col-sm-12">
						<?php echo $detail->content; ?>
					</div>
					
				</div>
			</div>
			<div class="col-sm-2" style="padding-left:0;">
				<?php require __DIR__.'/right.phtml';?>
			</div>
		</div>
	</div>
</div>

<!-- footer -->
<div id='footer'><?php require __DIR__.'/../ruiy/footer.phtml';?></div>
<script type="text/javascript" src="/ruiy/js/jquery.min.js"></script>
<script type="text/javascript" src="/ruiy/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="/ruiy/js/bootstrap.js"></script>
<script type="text/javascript" src="/ruiy/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/ruiy/js/main.js"></script>
<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1272959461'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1272959461%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
<script type="text/javascript" src="/ruiy/js/img-change.js"></script>
</body>
</html>