<?php 
  $zxid=Request::getIntParam('id');
$zx=json_decode(GreatAPI::Singleton()->FetchUrlData('/ServerZX/GetDetailById.cwg',[
  'id'=>$zxid,
])); // Cms_Servic e_Api_Contents_Default::getInstance()->get Item($zxid);
//var_dump($zx);die;
$arr=[];
foreach ($zx as $key => $value) {
	if($value->_cms_types_name=="新闻室")
	{
		$arr[$key]=$value;
	}
}


$meta->keywords=$zx->keywords;
if($zx->_if_jump_url){
  Response::redirect_url($zx->jump_url);
  die;
}

// 设定导航参数
$_level_bar1='/news/list';
$current_level_id=$zx->cms_types_id;
$level_types=Cms_Service_Api_Types::getInstance()->walkUp($current_level_id,290);

// 增加点击量
Cms_Service_Api_Contents_Default::getInstance()->view($zxid);





?>
<style type="text/css">
	#imgg p img{
		width: 100%;
	}
</style>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><?php echo $meta->title; ?></title>
    <meta name="description" content="<?php echo $meta->description; ?>" />
    <meta name="keywords" content="<?php echo $meta->keywords; ?>" />
    <link rel="shortcut icon" href="<?php echo $meta->favicon; ?>" />
    <link rel="bookmark" href="<?php echo $meta->favicon; ?>" type="image/x-icon"　/>
    <link rel="icon" href="<?php echo $meta->favgif; ?>" type="image/gif" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=0" />
    <meta name="baidu-site-verification" content="l9jDiF4kqd" />
	<meta name="baidu-site-verification" content="qvC3nD7GAI" />
	<link rel="stylesheet" type="text/css" href="/ruiy/css/style.css">
	<link rel="stylesheet" type="text/css" href="/ruiy/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/ruiy/css/bootstrap.css">
</head>
<body>
<header id="header"><?php require __DIR__.'/../ruiy/header.phtml';?></header>
<!-- banner -->
<div class="banner">
	<div id="myCarousel1" class="carousel slide">
	  
	    <div class="carousel-inner">
	        <?php Cms_Widget::factory('Ad')->display(Cms_Service_Api_Contents_Banner::getInstance()->getListByTypeId(100099),['need_LR'=>true,]); ?>
	    </div>
    </div>
    
</div>
<style type="text/css">
	@media (min-width: 1200px){
	.banner {
	    width: 100%;
	    height: 365px;
	}
}
@media (min-width: 992px){
.banner {
    width: 100%;
	    height: 365px;

}
@media (min-width: 768px){
.banner {
    width: 100%;
	    height: 365px;
    
}
</style>
<!-- nav -->
<div id="nav" class="navr">
	<ul style='margin: 0;'>
		<li><a href="/cn/zh/breakingpoint-consulting.html">睿远咨询</a><span class="xian">|</span></li>
		<li><a href="/cn/zh/contact-us.html">联系我们</a><span class="xian">|</span></li>
		<li><a href="https://www.liepin.com/zhaopin/?sfrom=click-pc_homepage-centre_searchbox-search_new&d_sfrom=search_fp&key=%E7%9D%BF%E4%BB%AA">加入睿远</a><span class="xian">|</span></li>
		<li><a class='active' href="/cn/zh/news-room.html">新闻室</a><span class="xian">|</span></li>
		<li><a href="http://ibreakingpoint.huodongxing.com ">活动沙龙</a></li>
	</ul>
</div>
<!-- content -->
<style type="text/css">
	.wenz .item:hover{
		border-bottom:1px solid #c7161e;
	}
</style>
<div class='content'>
	<div class="container">
		<div class="row">
			<div class="col-sm-10 new_list">
				<div class="wenz">
					<div class="top">
						<p class="title"><?php echo $zx->title;
					         //echo $zx->_cms_types_name;

                            //var_dump($zx);
						?></p>

						<div class="date">
							<!-- <span>日期：<?php echo $zx->create_time; ?></span> -->
							<span>日期：<?php $time=strtotime($zx->create_time);
                                         echo date('Y-m-d',$time); ?></span>
							<span style="margin-left:40px;">浏览：<?php echo $zx->view_count; ?></span>
							<!-- <span><?php echo $zx->view_count; ?></span> -->
						</div>
						<hr class='h'>
					</div>
					<div id='imgg' class="center">
					 
                                  <?php echo $zx->content;
                                   //echo "<pre>";
                                   // var_dump($zx);
                                   //var_dump($arr);
                                  ?>
					</div>
					<div class="bottom">
 <?php  // 原生----------------------------------------?>

								<div class="prev"
                                  <?php  if($arr['_last_content']==null){?>
                                  style="display: none;" 
                                   <?php }?>
								>上一篇：
										<?php 
										if($arr['_last_content']!=null){ 
									    ?>
									        <a class='active item' href="?id=<?php echo $zx->_last_content->id; ?>">
									          <?php echo $arr['_last_content']->title; ?>
									        </a>
								          <?php
								           }else{
								          ?>
									    <del>没有了</del>
									     <?php }?>
									   </p>

								 </div>


								 <div class="next" 
								 <?php  if($arr['_next_content']==null){?>
                                   style="display: none;" 
                                   <?php }?>
								 >下一篇：
                      
										<?php if($arr['_last_content']!=null&&isset($arr['_next_content']->title)){ ?>


                   


									           	 <a class='item' href="?id=<?php echo $zx->_next_content->id; ?>">
										         <?php echo $arr['_next_content']->title; ?></a>
								         <?php }else{if($arr['_next_content']!=null){ ?>
                               <a class='item' href="?id=<?php echo $zx->_next_content->id; ?>">
										         <?php echo $arr['_next_content']->title; ?></a>         
                                                 <?php }else{?>

							           <del>没有了</del>
							           <?php } }?></p>
					             </div>
					</div>




			    <div class="copyright-ad">
						<div class="copyright-ad-pic" style="position: relative;">
							<?php Cms_Widget::factory('Ad')->display(Cms_Service_Api_Contents_Banner::getInstance()->getListByTypeId(313)); ?>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-2" style="padding-left:0;">
				<div class="box">
					<p class="title"><span class="xian">|</span>关注我们</p>
					<p style='margin:15px;'>
						<a target="_blank" href="https://www.facebook.com/ibreakingpoint"><img target="_blank" src="/ruiy/images/zx_03.jpg"></a>
						<a href="http://www.linkedin.com/groups?gid=3291404"><img src="/ruiy/images/zx_05.jpg"></a>
						<a id='cimg' href="#"><img src="/ruiy/images/zx_07.jpg"></a>
					</p>
					<p id='pimg' style='text-align:center;display: none;'><img style='width:80%;' src="/ruiy/images/er.jpg"></p>
				</div>
				<div class="box">
					<p class='title'><span class="xian">|</span>市场合作</p>
					<p class='s1'>电话：021-34010561</p>
					<p class='s1'>邮箱：even.zhang@ibreaking point.com</p>
				</div>
				<?php $b=fetch_json_data('/ServerZX/GetListAll.cwg?count=5&page=1&cms_types_id=100120')->Data; ?>
				<div class="box">
					<p class='title'><span class="xian">|</span>阅读参考</p>
					 <?php                         
                        
                          foreach ($b as $key => $value) {
                          	//var_dump($value);
                      
                      ?>
                    <a href="/news/<?php echo $value->id.'.html';?>" style='margin-right: 0px;'>
					<p class='wei'><?php echo $value->title;?></p>
					<p class='s1 w1'><?php echo $value->summary;?></p>
					</a>

                   <?php } ?>
					<!-- <p class='wei'>. 微信文章标题</p>
					<p class='s1 w1'>微信文章介绍简介微信微信文章介绍</p>
					<p class='s1 w1'>简介微信文章介绍简介</p> -->
				</div>
			</div>
		</div>
	</div>
</div>

<!-- footer -->
<div id='footer'><?php require __DIR__.'/../ruiy/footer.phtml';?></div>
<script type="text/javascript" src="/ruiy/js/jquery.min.js"></script>
<script type="text/javascript" src="/ruiy/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="/ruiy/js/bootstrap.js"></script>
<script type="text/javascript" src="/ruiy/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/ruiy/js/main.js"></script>
<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1272959461'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1272959461%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
</body>
</html>