<!DOCTYPE html>
<html>
<head>
<div class="banner">
  <div id="myCarousel1" class="carousel slide">
     <?php //Cms_Widget::factory('Ad')->display(Cms_Service_Api_Contents_Banner::getInstance()->getListByTypeId(),['need_LR'=>true,]); ?>
      <img style='width: 100%' src="/ruiy/images/bm_01.png">
    </div>
</div>
<div class='container'>
  <div style='text-align:center;font-size:14px;color:#252525;padding-top:20px;'>
    <p style='font-size:23px;margin-top:143px;'>提交成功!</p>
    <p>华东会员如需交纳会费, 请与秘书长联系，微信号:zillitha</p>
  </div>

  <!-- <div class="center " style='text-align: center;'>
    <img src="/ruiy/images/zhongouyuxie.jpg" width="30%" height="30%">
    <img src="/ruiy/images/loog.png" width='22%' style='position: relative;top:-108px;'>
    </div>-->
</div> 

 <div class="bottom" style='text-align: center;color: #fff;font-size:18px;margin: 48px 0;'>
   <div style="position: relative;"><div style="height:55px;width:150px;display: inline-block;position: relative;">
     <a href="#" style='display:block;height:55px;width:150px;color: #fff;text-decoration:none;position: absolute;top:15px;margin-left: 25px;font-family: "微软雅黑";'>Powered by 
     </a>
   </div>
   <img src="/ruiy/images/logob.png" style="" >
  </div>
</div>





<style type="text/css">
  .container{
    width:80%;
    height:400px;
    background:#fff;
    margin:24px auto;
    margin-bottom: 100px;
  }
    body{
        padding:0;margin: 0;
        background-image: url(/ruiy/images/bm_bg.jpg);
        background-repeat: no-repeat;
        background-position: 0% 100%;
        background-size: cover;}
  }
  #foot{
    
    }
</style>
  </body>
</html>
