<div class="footer" style="height:660px">
	<div class='container'>
		<div class="row">
			<div class="col-sm-2">
				<ul>
					<li class="title">Industries</li>
					<li class='yi'>
						<a href="/pc/ruiy/dealer/">Automotive</a>
						<ul>
							<li class='er'><a href="/pc/ruiy/engine" style="width: 236px;">Automaker</a></li>
							<li class='er'><a href="/pc/ruiy/dealer/">Dealers</a></li>
						</ul>
					</li>
					<li class='yi'><a href="/pc/ruiy/land/">Real Estate </a></li>
					<li class='yi'><a href="/pc/ruiy/retail/">New Retail</a></li>
				</ul>
			</div>
			<div class="col-sm-2" style='width:26%;'>
				<ul style="position:relative;width:100%;">
					<li class="title">Management Consulting </li>
					<li class='yi'>
						<a href="/pc/ruiy/innovate/">Strategy Transformation</a>
						<ul>
							<li class='er'><a href="/pc/ruiy/innovate/">New Retail</a></li>
							<li class='er'><a href="/pc/ruiy/innovate/">Digitized Operation</a></li>
						</ul>
					</li>
					<li class='yi'>
						<a href="/pc/ruiy/busi/">Business Management</a>
						<ul>
							<li class='er'><a href="/pc/ruiy/busi/">Business/Finance Integration</a></li>
							<li class='er'><a href="/pc/ruiy/busi/">Comprehensive Budget Management</a></li>
							<li class='er'><a href="/pc/ruiy/busi/">Performance Management</a></li>
						</ul>
					</li>
					<li class='yi'>
						<a href="/pc/ruiy/itconsult/">IT Strategic Planning</a>
						<ul>
							<li class='er'><a href="/pc/ruiy/itconsult/">Business Strategy & IT Planning</a></li>
							<li class='er'><a href="/pc/ruiy/itconsult/">IT Governance</a></li>
							<li class='er'><a href="/pc/ruiy/itconsult/">PMP & ITIL</a></li>
							<li class='er'><a href="/pc/ruiy/itconsult/">Risk Management & Value Assessment</a></li>
							<!--<li class='er'><a href="/pc/ruiy/itconsult/">项目管理及运维协同体系 
							（PMP 	&amp; ITIL）</a></li>-->
							<!-- <li class='er ch'><a href="/pc/ruiy/itconsult/">项目管理及运维协同体系 
							（PMP 	&amp; ITIL）</a></li> -->
						</ul>
					</li>
				</ul>
			</div>
			<div class="col-sm-2" style="margin-left: 25px;">
				<ul>
					<li class="title">Software</li>
					<li class='yi'>
						<a href="/pc/ruiy/salesforce/">Salesforce</a>
						<ul>
							<li class='er'><a href="/pc/ruiy/salesforce/">Sales Cloud</a></li>
							<li class='er'><a href="/pc/ruiy/salesforce/">Service Cloud</a></li>
							<li class='er'><a href="/pc/ruiy/salesforce/">Pardot</a></li>
							<li class='er'><a href="/pc/ruiy/salesforce/">Community Cloud</a></li>
						</ul>
					</li>
					<li class='yi'>
						<a href="/pc/ruiy/spa/">SAP</a>
						<ul>
							<li class='er'><a href="/pc/ruiy/spa/">Hybris Hybris-Marketing</a></li>
							<li class='er'><a href="/pc/ruiy/spa/">Hybris Marketing</a></li>
							<li class='er'><a href="/pc/ruiy/spa/">Hybris C4C</a></li>
							<li class='er'><a href="/pc/ruiy/spa/">DBM</a></li>
							<li class='er'><a href="/pc/ruiy/spa/">S4</a></li>
							<li class='er'><a href="/pc/ruiy/spa/">HANA</a></li>
							<li class='er'><a href="/pc/ruiy/spa/">BPC</a></li>
						</ul>
					</li>
				</ul>
			</div>
			<div class="col-sm-2" style="margin-right:20px;margin-left: 25px;">
				<ul style="height: 445px;">
					<li class="title">About Us</li>
					<li class='yi'><a href="/pc/ruiy/consult/">Breakingpoint Consulting</a></li>
					<li class='yi'><a href="/pc/ruiy/lianx/">Contact Us</a></li>
					<li class='yi'><a href="http://search.51job.com/list/020000,000000,0000,00,9,99,%25E4%25B8%258A%25E6%25B5%25B7%25E7%259D%25BF%25E8%25BF%259C%25E8%25BD%25AF%25E4%25BB%25B6%25E4%25BF%25A1%25E6%2581%25AF%25E5%2592%25A8%25E8%25AF%25A2%25E6%259C%2589%25E9%2599%2590%25E5%2585%25AC%25E5%258F%25B8,1,1.html?lang=c&stype=&postchannel=0000&workyear=99&cotype=99&degreefrom=99&jobterm=99&companysize=99&providesalary=99&lonlat=0%2C0&radius=-1&ord_field=0&confirmdate=9&fromType=&dibiaoid=0&address=&line=&specialarea=00&from=&welfare=" target="_blank">Join Us</a></li>
					<li class='yi'><a href="/pc/ruiy/news/">News Room</a></li>
					<li class='yi'><a href="http://ibreakingpoint.huodongxing.com " target="_blank">Activities</a></li>
					<li style="position: absolute;bottom: 0px;"><img id='erw' style='width:150px;opacity:0;' src="/ruiy/images/er.jpg"></li>
				</ul>
			</div>
			<div class="col-sm-3" style="width: 150px;">
				<ul style="height: 445px;">
					<li class="title">Partner</li>
					<li class='img' style="margin-left:20px;margin-top: 50px;"><a href="https://www.salesforce.com/cn/ " target="_blank"><img style="width:70px;" src="/ruiy/images/yun.jpg"></a></li>
					<li class='img' style="margin-left:20px;"><a href="https://www.sap.com/china/index.html?campaigncode=CRM-CN17-PPC-BRDBZFC&source=PPC-CN-Baidu_BrandZone-BZ-TITLE " target="_blank"><img style="width:70px;margin-top: 5px;" src="/ruiy/images/sap.jpg"></a></li>
					<div style="position: absolute;bottom: 0px;">
						<li class='xtub' style="margin-left:-30px;margin-top:145px;">
							<a href="https://www.facebook.com/ibreakingpoint" target="_blank"><img src="/ruiy/images/t1.jpg"></a>
							<a href="http://www.linkedin.com/groups?gid=3291404" target="_blank"><img src="/ruiy/images/t2.jpg"></a>
							<a id='er' href="javascript:;"><img src="/ruiy/images/t3.png"></a>
						</li>
						<li class='yi' style='color:#fff;font-size:16px;margin-top:10px;margin-left:-30px;width: 290px;'>Customer Inquiry：400-820-7332</li>
						<li class='yi' style='color:#fff;font-size:16px;margin-top:10px;margin-left:-30px;width: 320px;'>Market Collaboration ：021-34010561</li>
					</div>
				</ul>
			</div>

		</div>
	</div>
	<div class="col-sm-12 foot">&copy; 2018 ibreakingpoint.com &nbsp; Shanghai ruiyuan software information consulting co., LTD.  All rights reserved for Shanghai ICP 11045576 -1.</div>
</div>
<script type="text/javascript" src='/ruiy/js/jquery-2.1.1.min.js'></script>
<script type="text/javascript">
	$('#er').mouseenter(function(){
		$('#erw').css('opacity',1);
	})
	$('#er').mouseleave(function(){
		$('#erw').css('opacity',0);
	})

</script>