<div id="dead" class="header">
	<div class="container">
		<div class="row">
			<div class="col-sm-2">
				<a href="/pc/euiy/index"><img id="logo" src="/ruiy/images/logob.png"></a>
			</div>
			<div class="col-sm-6 header-title">
				<ul id='navv'>
					<li class='item ' ><div class="itemTopDiv"></div><div class="itemDiv">
          <a style='width:70px;' href="/pc/enruiy/index/" class="item-a">Home
          </a>
          </div>
          </li>
					<li class='item'><div class="itemTopDiv"></div><div class="itemDiv serveDiv"><a style='width:80px;'  href="/pc/enruiy/serve/">Services</a></div>
				        <ul >
				           	<li class='er' class='item_son' style="width:240px;"><a href="/pc/enruiy/serve/" style="text-transform: capitalize;">Management Consulting</a>
					           	<div class='er_son' style="width:230px;">
					           		<p class='item_son' style="width:250px;"><a href="/pc/enruiy/innovate/" style="font-size:14px;">Strategy Transformation</a></p>
					           		<p class='item_son' style="width:250px;"><a href="/pc/enruiy/busi/" style="font-size:14px;">Business Management</a></p>
					           		<p class='item_son' style="width:250px;"><a href="/pc/enruiy/itconsult/" style="font-size:14px;">IT Strategic Planning</a></p>
					           	</div>
				           	</li>
				           	<li class='er' class='item_son'><a  href="/pc/enruiy/softwave/" style="text-transform: capitalize;">Software</a>
				           		<div class='er_son'>
				           		    <p class='item_son'><a href="/pc/enruiy/spa/" style="font-size:14px;">SAP</a></p>
					           		<p class='item_son'><a style='text-transform: capitalize;font-size:14px;' href="/pc/enruiy/salesforce/">Salesforce</a></p>
					           	</div>
					        </li>	
				        </ul> 
					</li> 
					<li class='item'><div class="itemTopDiv"></div><div class="itemDiv"><a  href="javascript:;" style='width:90px'>Industries</a></div>
						 <ul >
				           	<li class='er' class='item_son'><a href="/pc/enruiy/engine/" style="text-transform: capitalize;">Automobile</a>
					           	<div class='er_son'>
					           		<p class='item_son'><a href="/pc/enruiy/engine/" style="font-size:14px;">Automaker</a></p>
					           		<p class='item_son'><a href="/pc/enruiy/dealer/" style="font-size:14px;">Dealers</a></p>
					           	</div>
				           	</li>
				           	<li class='item_son'><a href="/pc/enruiy/land/">Real Estate</a></li>
				           	<li class='item_son'><a href="/pc/enruiy/retail/">New Retail</a></li>
				        </ul>
					</li>	
					<li class='item'><div class="itemTopDiv"></div><div class="itemDiv"><a href="javascript:;" style='width:85px;'>About us</a></div>
						 <ul >
				           	<li class='item_son' style="width:245px;"><a href="/pc/enruiy/consult/">Breakingpoint Consulting</a>
					        <li class='item_son'><a href="/pc/enruiy/lianx/">Contact us</a>
				           	<li class='item_son'><a href="http://search.51job.com/list/020000,000000,0000,00,9,99,%25E4%25B8%258A%25E6%25B5%25B7%25E7%259D%25BF%25E8%25BF%259C%25E8%25BD%25AF%25E4%25BB%25B6%25E4%25BF%25A1%25E6%2581%25AF%25E5%2592%25A8%25E8%25AF%25A2%25E6%259C%2589%25E9%2599%2590%25E5%2585%25AC%25E5%258F%25B8,1,1.html?lang=c&stype=&postchannel=0000&workyear=99&cotype=99&degreefrom=99&jobterm=99&companysize=99&providesalary=99&lonlat=0%2C0&radius=-1&ord_field=0&confirmdate=9&fromType=&dibiaoid=0&address=&line=&specialarea=00&from=&welfare= " target="_blank">Join Us</a></li>
				           	<li class='item_son' style="width:245px;"><a href="/pc/enruiy/news/">News Room</a>
				           	<li class='item_son' style="width:245px;"><a href="http://ibreakingpoint.huodongxing.com " target="_blank">Activities & Salon</a></li>
				        </ul>
					
							<li class='item'><a style='width:70px;' href="http://search.51job.com/list/020000,000000,0000,00,9,99,%25E4%25B8%258A%25E6%25B5%25B7%25E7%259D%25BF%25E8%25BF%259C%25E8%25BD%25AF%25E4%25BB%25B6%25E4%25BF%25A1%25E6%2581%25AF%25E5%2592%25A8%25E8%25AF%25A2%25E6%259C%2589%25E9%2599%2590%25E5%2585%25AC%25E5%258F%25B8,1,1.html?lang=c&stype=&postchannel=0000&workyear=99&cotype=99&degreefrom=99&jobterm=99&companysize=99&providesalary=99&lonlat=0%2C0&radius=-1&ord_field=0&confirmdate=9&fromType=&dibiaoid=0&address=&line=&specialarea=00&from=&welfare= " target="_blank">Join us</a></li>
					</li>
				</ul>
				
			</div>
			<div class="col-sm-2 phone"><a style="font-size:16px; text-align:right;margin-left: 47px;" href="#">400-820-7332</a></div>
			<div class="col-sm-2 lian">	<a class="l1" href="/pc/enruiy/lianx" >Contact us</a><a class="l2" id="zhong" href="JavaScript:;">中</a></div>
		</div>
	</div>
</div>
<script type="text/javascript" src='/ruiy/js/jquery-2.1.1.min.js'></script>
<script type="text/javascript">
	$(document).ready(function() { 
 $('#navv li').hover(function() {
  $('ul', this).slideDown(200);
  $(this).children('a:first').addClass("hov");
 }, function() {
  $('ul', this).slideUp(100);
  $(this).children('a:first').removeClass("hov");  
 });
 $('.er').hover(function() {
  $('div', this).slideDown(200);
  $(this).children('a:first').addClass("hov");
 }, function() {
  $('div', this).slideUp(100);
  $(this).children('a:first').removeClass("hov");  
 });
});
</script>

<style type="text/css">
  

 .wrap { width: 800px; margin: 0 auto; }
  #navv { margin: 0; padding: 0; list-style: none; border-bottom-left-radius: 4px; -moz-border-radius-bottom-left: 4px; -webkit-border-bottom-left-radius: 4px; border-bottom-right-radius: 4px; -moz-border-radius-bottom-right: 4px; -webkit-border-bottom-right-radius: 4px; height: 50px; padding-left: 15px; padding-right: 15px;  text-align:center;}
  #navv li { float: left; display: block; background: none; position: relative; z-index: 999; margin: 0 1px; }
  #navv li a { 
    display: block;
      padding: 0;
      font-weight: 14px;
      line-height: 70px;
      text-decoration: none;
      color: #fff;
      zoom: 1;
      border-left: 1px solid transparent;
      border-right: 1px solid transparent;
      font-size: 14px; 
  }
  #navv li a:hover{color:#c7161e;}
  #navv .item a{border-bottom: 2px solid transparent;}
  .item > ul{
    padding: 11px 0;
  }

  #navv .item_son >a{
    text-transform: capitalize;

  }
  #navv .er_son p a{
    font-size:8px;
  }
  #navv .item_son > a.hov { color:#c7161e; }
  #navv ul { 
  		position: absolute;top:70px; left: 1px; display: none; margin: 0; padding: 0; list-style: none; -moz-box-shadow: 0 1px 3px rgba(0,0,0,0.2); -o-box-shadow: 0 1px 3px rgba(0,0,0,0.2); box-shadow: 0 1px 3px rgba(0,0,0,0.2); -webkit-box-shadow: 0 1px 3px rgba(0,0,0,0.2); 
  		padding: 5px 0;
  		background:#fff;
  		box-shadow: 1px 1px 10px rgba(0,0,0,.09);
  		border-top: 2px solid #c7161e;
  	}
  #navv ul li { 
  	width: 149px;
      float: left;
      text-align: left;
      color: #333333;
      padding: 7px 20px;
   }
  #navv ul li:hover { border-left: 0px solid transparent; border-right: 0px solid transparent; }
  #navv ul a { 
  	display: block;
      height: 25px;
      line-height: 20px;
      padding: 2px 16px;
      color: #666;
      border-bottom: 1px solid transparent;
      text-transform: capitalize;
      color: #797979;
      font-weight: normal;
  }

  #navv ul a:hover { text-decoration: none; border-right-color: transparent; border-left-color: transparent; background: transparent; color: #c7161e; }
  * html #navv ul { margin: 0 0 0 -2px; }
  .clearfix:after { content: "."; display: block; clear: both; visibility: hidden; line-height: 0; height: 0; }
  .clearfix { display: inline-block; }
  html[xmlns] .clearfix { display: block; }
  * html .clearfix { height: 1%; }
  .er_son{
  	position: absolute;
      left: 150px;
      display: none;
      background: #fff;
      width: 150px;
      top: -5px;
      padding:10px 0 10px;
      box-shadow: 1px 1px 10px rgba(0,0,0,.07);
  }
  .er_son a:hover{color:#c7161e;}
  .item_son{padding:2px 20px;}
  .lian .l1:hover{
    border:none!important;
    background:#c7161e!important;
  }
   .itemTop, .itemlongTop, .itemMidTop,.itemSerTop{
    height: 3px;
    position: absolute;
    z-index:20;
    background: #c7161e;
  }
  .itemTop{
      width:70px;
  }
  .itemlongTop{
    width:90px;
  }
  .itemMidTop{
    width: 85px;
  }
  .itemSerTop{
    width:80px;
  }
  .smalBack,.longBack,.medBack,.serBack{

      background: rgba(128, 128, 128, 0.18);
      height: 71px;  
     /* box-sizing:border-box;  
  -moz-box-sizing:border-box; /* Firefox */  
  /*-webkit-box-sizing:border-box; */
      /*border-top:3px solid #c7161e;*/
    }
    .smalBack{
      width: 70px;
    }
  .longBack{
      width: 90px;
  }
  .medBack{
      width: 85px;
  }
  .serBack{
    width:80px;
  }
  #dead .l1{
    width:90px;
  }
</style>

<script type="text/javascript">
var navv = document.getElementById("navv");
var oHref = document.getElementsByClassName('item-a');
var oItemDiv = document.getElementsByClassName('itemDiv');
var oItemTopDiv = document.getElementsByClassName('itemTopDiv');
var oServer = document.getElementsByClassName('serveDiv')[0];
var serve = ["http://www.ibreakingpoint.com/pc/enruiy/serve/","http://www.ibreakingpoint.com/pc/enruiy/innovate/","http://www.ibreakingpoint.com/pc/enruiy/busi/","http://www.ibreakingpoint.com/pc/enruiy/itconsult/","http://www.ibreakingpoint.com/pc/enruiy/softwave/","http://www.ibreakingpoint.com/pc/enruiy/spa/","http://www.ibreakingpoint.com/pc/enruiy/salesforce/"];
var solute = ["http://www.ibreakingpoint.com/pc/enruiy/engine/","http://www.ibreakingpoint.com/pc/enruiy/engine/","http://www.ibreakingpoint.com/pc/enruiy/dealer/","http://www.ibreakingpoint.com/pc/enruiy/land/","http://www.ibreakingpoint.com/pc/enruiy/retail/"];
var about = ["http://www.ibreakingpoint.com/pc/enruiy/consult/","http://www.ibreakingpoint.com/pc/enruiy/lianx/","http://www.ibreakingpoint.com/pc/enruiy/news/"];
for(var i = 0;i<20;i++){
  if(serve[i] == window.location.href){
    oItemDiv[1].className = "itemDiv serBack";
    oItemTopDiv[1].className = "itemTopDiv itemSerTop";
  }else if(solute[i] == window.location.href){
    oItemDiv[2].className = "itemDiv longBack";
      oItemTopDiv[2].className = "itemTopDiv itemlongTop";
  }else if(about[i] == window.location.href){
    oItemDiv[3].className = "itemTopDiv medBack";
      oItemTopDiv[3].className = "itemTopDiv itemMidTop";
  }else if("http://www.ibreakingpoint.com/pc/enruiy/index/" == window.location.href){
    oItemDiv[0].className = "itemDiv smalBack";
    oItemTopDiv[0].className = "itemTopDiv itemTop";
  }
}

$("#zhong").click(function(){
  var $href = window.location.href;
  var h = $href.split("c/en");
  var hh = h[0]+"c/"+h[1];
  window.location.href = hh;
})

</script>

