<?php 
  $zxid=Request::getIntParam('id');
$zx=json_decode(GreatAPI::Singleton()->FetchUrlData('/ServerZX/GetDetailById.cwg',[
  'id'=>$zxid,
])); // Cms_Servic e_Api_Contents_Default::getInstance()->get Item($zxid);
//var_dump($zx);die;

$meta->keywords=$zx->keywords;
if($zx->_if_jump_url){
  Response::redirect_url($zx->jump_url);
  die;
}

// 设定导航参数
$_level_bar1='/news/list';
$current_level_id=$zx->cms_types_id;
$level_types=Cms_Service_Api_Types::getInstance()->walkUp($current_level_id,290);

// 增加点击量
Cms_Service_Api_Contents_Default::getInstance()->view($zxid);





?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><?php echo $meta->title; ?></title>
    <meta name="description" content="<?php echo $meta->description; ?>" />
    <meta name="keywords" content="<?php echo $meta->keywords; ?>" />
    <link rel="shortcut icon" href="<?php echo $meta->favicon; ?>" />
    <link rel="bookmark" href="<?php echo $meta->favicon; ?>" type="image/x-icon"　/>
    <link rel="icon" href="<?php echo $meta->favgif; ?>" type="image/gif" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=0" />
    <meta name="baidu-site-verification" content="l9jDiF4kqd" />
	<meta name="baidu-site-verification" content="qvC3nD7GAI" />
	<link rel="stylesheet" type="text/css" href="/ruiy/css/style.css">
	<link rel="stylesheet" type="text/css" href="/ruiy/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/ruiy/css/bootstrap.css">
</head>
<body>
<header id="header"><?php require __DIR__.'/../ruiy/header.phtml';?></header>
<!-- banner -->
<div class="banner">
	<div id="myCarousel1" class="carousel slide">
	  
	    <div class="carousel-inner">
	        <?php Cms_Widget::factory('Ad')->display(Cms_Service_Api_Contents_Banner::getInstance()->getListByTypeId(100099),['need_LR'=>true,]); ?>
	    </div>
    </div>
    
</div>
<!-- nav -->
<div id="nav" class="navr">
	<ul style='margin: 0;'>
		<li><a href="/pc/ruiy/consult">睿远咨询</a><span class="xian">|</span></li>
		<li><a href="/pc/ruiy/lianx">联系我们</a><span class="xian">|</span></li>
		<li><a href="http://search.51job.com/list/020000,000000,0000,00,9,99,%25E4%25B8%258A%25E6%25B5%25B7%25E7%259D%25BF%25E8%25BF%259C%25E8%25BD%25AF%25E4%25BB%25B6%25E4%25BF%25A1%25E6%2581%25AF%25E5%2592%25A8%25E8%25AF%25A2%25E6%259C%2589%25E9%2599%2590%25E5%2585%25AC%25E5%258F%25B8,1,1.html?lang=c&stype=&postchannel=0000&workyear=99&cotype=99&degreefrom=99&jobterm=99&companysize=99&providesalary=99&lonlat=0%2C0&radius=-1&ord_field=0&confirmdate=9&fromType=&dibiaoid=0&address=&line=&specialarea=00&from=&welfare= ">加入睿远</a><span class="xian">|</span></li>
		<li><a class='active' href="/pc/ruiy/news">新闻室</a><span class="xian">|</span></li>
		<li><a href="http://ibreakingpoint.huodongxing.com ">活动沙龙</a></li>
	</ul>
</div>
<!-- content -->
<style type="text/css">
	.wenz .item:hover{
		border-bottom:1px solid red;
	}
</style>
<div class='content'>
	<div class="container">
		<div class="row">
			<div class="col-sm-10 new_list">
				<div class="wenz">
					<div class="top">
						<p class="title"><?php echo $zx->title;

                               //var_dump($zx);
						?></p>

						<div class="date">
							<span>Date：<?php echo $zx->create_time; ?></span>
							<span style="margin-left:40px;">Viewed：<?php echo $zx->view_count; ?></span>
							<!-- <span><?php echo $zx->view_count; ?></span> -->
						</div>
						<hr class='h'>
					</div>
					<div class="center">
					 
                                  <?php echo $zx->content;?>
					</div>
					<div class="bottom">
								<div class="prev">上一篇：
										<?php 
										if($zx->_last_content!==null): 
									    ?>
									        <a class='active item' href="?id=<?php echo $zx->_last_content->id; ?>">
									          <?php echo $zx->_last_content->title; ?>
									        </a>
								          <?php
								           else:
								          ?>
									    <del>没有了</del>
									    <?php endif; ?></p>

								 </div>


								 <div class="next">下一篇：

										<?php if($zx->_next_content!==null): ?>
									           	 <a class='item' href="?id=<?php echo $zx->_next_content->id; ?>">
										         <?php echo $zx->_next_content->title; ?></a>
								         <?php else: ?>
							           <del>没有了</del>
							           <?php endif; ?></p>
					             </div>
					</div>




			    <div class="copyright-ad">
						<div class="copyright-ad-pic" style="position: relative;">
							<?php Cms_Widget::factory('Ad')->display(Cms_Service_Api_Contents_Banner::getInstance()->getListByTypeId(313)); ?>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-2" style="padding-left:0;">
				<div class="box">
					<p class="title"><span class="xian">|</span>关注我们</p>
					<p style='margin:15px;'>
						<a href="https://www.facebook.com/ibreakingpoint"><img src="/ruiy/images/zx_03.jpg"></a>
						<a href="http://www.linkedin.com/groups?gid=3291404"><img src="/ruiy/images/zx_05.jpg"></a>
						<a id='cimg' href="#"><img src="/ruiy/images/zx_07.jpg"></a>
					</p>
					<p id='pimg' style='text-align:center;display: none;'><img style='width:80%;' src="/ruiy/images/er.jpg"></p>
				</div>
				<div class="box">
					<p class='title'><span class="xian">|</span>市场合作</p>
					<p class='s1'>电话：021-34010561</p>
					<p class='s1'>邮箱：even.zhang@ibreaking point.com</p>
				</div>
				<?php $b=fetch_json_data('/ServerZX/GetListAll.cwg?count=5&page=1&cms_types_id=100120')->Data; ?>
				<div class="box">
					<p class='title'><span class="xian">|</span>阅读参考</p>
					 <?php                         
                        
                          foreach ($b as $key => $value) {
                          	//var_dump($value);
                      
                      ?>
                    <a href="/news/<?php echo $value->id.'.html';?>" style='margin-right: 0px;'>
					<p class='wei'><?php echo $value->title;?></p>
					<p class='s1 w1'><?php echo $value->summary;?></p>
					</a>

                   <?php } ?>
					<!-- <p class='wei'>. 微信文章标题</p>
					<p class='s1 w1'>微信文章介绍简介微信微信文章介绍</p>
					<p class='s1 w1'>简介微信文章介绍简介</p> -->
				</div>
			</div>
		</div>
	</div>
</div>

<!-- footer -->
<div id='footer'><?php require __DIR__.'/../ruiy/footer.phtml';?></div>
<script type="text/javascript" src="/ruiy/js/jquery.min.js"></script>
<script type="text/javascript" src="/ruiy/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="/ruiy/js/bootstrap.js"></script>
<script type="text/javascript" src="/ruiy/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/ruiy/js/main.js"></script>
</body>
</html>