  <!DOCTYPE html>
  <html>
  <head>
    <title></title>
    <style type="text/css">
      .box .lix a{
        display: block;
          width: 200px;
          text-align: center;
          background: #c7161e;
          line-height: 30px;
          color: #fff;
          margin: 0 auto;
          border-radius: 2px;
      }

    </style>
  </head>
  <body>
  <div class="right">
        <div class="box">
          <p class="title"><span class="xian">|</span>Contact us</p>
          <p class='lix'><a href="/pc/enruiy/lianx/">Contact us via online form</a></p>
        </div>
        <div class="box">
          <p class="title"><span class="xian">|</span>Follow us</p>
          <p style='margin:15px;'>
            <a target="_blank" href="https://www.facebook.com/ibreakingpoint"><img src="/ruiy/images/zx_03.jpg"></a>
            <a target="_blank" href="http://www.linkedin.com/groups?gid=3291404"><img src="/ruiy/images/zx_05.jpg"></a>
            <a id='cimg' href="javascript:;"><img src="/ruiy/images/zx_07.jpg"></a>
          </p>
          <p id='pimg' style='text-align:center;display: none;'><img style='width:80%;' src="/ruiy/images/er.jpg"></p>
        </div>
        <div class="box else-read" style="display: none;">
          <p class='title'><span class="xian">|</span>Explore Content</p>
               <?php $b=fetch_json_data('/ServerZX/GetListAll.cwg?count=5&page=1&cms_types_id=100121')->Data; ?>
              <?php                         
                        
                          foreach ($b as $key => $value) {
                            //var_dump($value);
                      
                      ?>
                   <a href="/news/<?php echo $value->id.'.html';?>" style='margin-right: 0px;' target="_blank">
                    <p class='wei'><?php echo $value->title;?></p>
                    <p class='s1 w1'><?php echo $value->summary;?></p>
                  </a>
              <?php } ?>
          <!-- <p class='wei'>. 微信文章标题</p>
          <p class='s1 w1'>微信文章介绍简介微信微信文章介绍</p>
          <p class='s1 w1'>简介微信文章介绍简介</p> -->
        </div>
        <div class="box engine-read" style="display: none;">
          <p class='title'><span class="xian">|</span><span class="page-title" style="font-size: 16px;"></span>Explore Content:</p>
               <?php $b=fetch_json_data('/ServerZX/GetListAll.cwg?count=5&page=1&cms_types_id=100154')->Data; ?>
              <?php                         
                        
                          foreach ($b as $key => $value) {
                            //var_dump($value);
                      
                      ?>
                   <a href="/news/<?php echo $value->id.'.html';?>" style='margin-right: 0px;' target="_blank">
                    <p class='wei'><?php echo $value->title;?></p>
                    <p class='s1 w1'><?php echo $value->summary;?></p>
                  </a>
              <?php } ?>
          <!-- <p class='wei'>. 微信文章标题</p>
          <p class='s1 w1'>微信文章介绍简介微信微信文章介绍</p>
          <p class='s1 w1'>简介微信文章介绍简介</p> -->
        </div>
          <div class="box land-read" style="display: none;">
          <p class='title'><span class="xian">|</span><span class="page-title" style="font-size: 16px;"></span>Explore Content</p>
               <?php $b=fetch_json_data('/ServerZX/GetListAll.cwg?count=5&page=1&cms_types_id=100153')->Data; ?>
              <?php                         
                        
                          foreach ($b as $key => $value) {
                            //var_dump($value);
                      
                      ?>
                   <a href="/news/<?php echo $value->id.'.html';?>" style='margin-right: 0px;' target="_blank">
                    <p class='wei'><?php echo $value->title;?></p>
                    <p class='s1 w1'><?php echo $value->summary;?></p>
                  </a>
              <?php } ?>
          <!-- <p class='wei'>. 微信文章标题</p>
          <p class='s1 w1'>微信文章介绍简介微信微信文章介绍</p>
          <p class='s1 w1'>简介微信文章介绍简介</p> -->
        </div>
          <div class="box retail-read" style="display: none;">
          <p class='title'><span class="xian">|</span><span class="page-title" style="font-size: 16px;"></span>Explore Content</p>
               <?php $b=fetch_json_data('/ServerZX/GetListAll.cwg?count=5&page=1&cms_types_id=100152')->Data; ?>
              <?php                         
                        
                          foreach ($b as $key => $value) {
                            //var_dump($value);
                      
                      ?>
                   <a href="/news/<?php echo $value->id.'.html';?>" style='margin-right: 0px;' target="_blank">
                    <p class='wei'><?php echo $value->title;?></p>
                    <p class='s1 w1'><?php echo $value->summary;?></p>
                  </a>
              <?php } ?>
          <!-- <p class='wei'>. 微信文章标题</p>
          <p class='s1 w1'>微信文章介绍简介微信微信文章介绍</p>
          <p class='s1 w1'>简介微信文章介绍简介</p> -->
        </div>

  </div>
  </body>
  <script type="text/javascript">
    var pageTitle = document.getElementsByClassName("page-title");
        var xian = document.getElementsByClassName("xian");
    var engine = ["http://www.ibreakingpoint.com/pc/enruiy/engine/","http://www.ibreakingpoint.com/pc/enruiy/dealer/"];
    var land = "http://www.ibreakingpoint.com/pc/enruiy/land/";
    var retail = "http://www.ibreakingpoint.com/pc/enruiy/retail/";
    var title = ["Engine-","Land-","Retail-"];
    console.log(pageTitle[0].innerHTML);
        if(engine[0] == window.location.href){
          pageTitle[0].innerHTML = title[0];
          $('.engine-read').css('display','block');
        }else if(engine[1] == window.location.href){
          pageTitle[0].innerHTML = title[0];
          $('.engine-read').css('display','block');
        }else if(land == window.location.href){
                    console.log(pageTitle[1]);
          pageTitle[1].innerHTML = title[1];
          $('.land-read').css('display','block');         
        }
        else if(retail == window.location.href){
          pageTitle[2].innerHTML = title[2];
          $('.retail-read').css('display','block');
        }else{
          $('.else-read').css('display','block');
        }
  </script>
  </html>