<!DOCTYPE html>
<html>
<head>
<div class="banner">
  <div id="myCarousel1" class="carousel slide">
     <?php //Cms_Widget::factory('Ad')->display(Cms_Service_Api_Contents_Banner::getInstance()->getListByTypeId(),['need_LR'=>true,]); ?>
      <img style='width: 100%' src="/ruiy/images/bm_01.png">
    </div>
</div>
<div class='container'>
  <div style='text-align:center;font-size:14px;color:#252525;padding-top:20px;'>
    <p style='font-size:23px;'>提交成功!</p>
    <p>华东会员如需交纳会费, 请与秘书长联系，微信号:zillitha</p>
  </div>

  <!-- <div class="center " style='text-align: center;'>
    <img src="/ruiy/images/zhongouyuxie.jpg" width="30%" height="30%">
    <img src="/ruiy/images/loog.png" width='22%' style='position: relative;top:-108px;'>
    </div>-->
</div> 
<div style='position: relative;
    text-align: center;
    width:80%;
    margin: 30px  auto;
    color: #fff;
    font-size:14px;
    '>
  <span>由</span>
  <img style='width:20%' src="/ruiy/images/logob.png">
  <span>提供技术支持</span>
</div>




<style type="text/css">
  .container{
    width:80%;
    height:400px;
    background:#fff;
    margin:24px auto;
    margin-bottom: 100px;
  }
    body{
        padding:0;margin: 0;
        background-image: url(/ruiy/images/bm_bg.jpg);
        background-repeat: no-repeat;
        background-position: 0% 100%;
        background-size: cover;}
  }
  #foot{
    
    }
</style>
  </body>
</html>
