	<!DOCTYPE html>
	<html>
	<head>
		<title></title>
	</head>
	<body>
	<div class="right">
				<div class="box">
					<p class="title"><span class="xian">|</span>关注我们</p>
					<p style='margin:15px;'>
						<a href="#"><img src="/ruiy/images/zx_03.jpg"></a>
						<a href="#"><img src="/ruiy/images/zx_05.jpg"></a>
						<a href="#"><img src="/ruiy/images/zx_07.jpg"></a>
					</p>
				</div>
				<div class="box">
					<p class='title'><span class="xian">|</span>市场合作</p>
					<p class='s1'>电话：+86 3401 0561</p>
					<p class='s1'>邮箱：event.zhang@ibreaking point.com</p>
				</div>
				<div class="box">
					<p class='title'><span class="xian">|</span>阅读参考</p>
					<p class='wei'>. 微信文章标题</p>
					<p class='s1 w1'>微信文章介绍简介微信文章介绍</p>
					<p class='s1 w1'>简介微信文章介绍简介</p>
					<p class='wei'>. 微信文章标题</p>
					<p class='s1 w1'>微信文章介绍简介微信微信文章介绍</p>
					<p class='s1 w1'>简介微信文章介绍简介</p>
				</div>
	</div>
	</body>
	</html>