 <!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><?php echo $meta->title; ?></title>
    <meta name="description" content="<?php echo $meta->description; ?>" />
    <meta name="keywords" content="<?php echo $meta->keywords; ?>" />
    <link rel="shortcut icon" href="<?php echo $meta->favicon; ?>" />
    <link rel="bookmark" href="<?php echo $meta->favicon; ?>" type="image/x-icon"　/>
    <link rel="icon" href="<?php echo $meta->favgif; ?>" type="image/gif" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=0" />
    <meta name="baidu-site-verification" content="l9jDiF4kqd" />
	<meta name="baidu-site-verification" content="qvC3nD7GAI" />

	<link rel="stylesheet" type="text/css" href="/ruiy/css/style.css">
	<link rel="stylesheet" type="text/css" href="/ruiy/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/ruiy/css/bootstrap.css">
<style type="text/css">
  .content .container .hr{
    width: 100%;
   }
  body .content .container .box{
    margin-top: 20px;
    width: 100%;
  }
  .container .content3 .descriptdiv{
       height: 188px;
      padding: 22px;
  }
  .container .content3 .descript-context{
    height:100%;
  }
  .container .content1 .f_f_1,
    .container .content1 .f_f_2
  {
    width: 69%;
  }
  .content .container{
    padding: 0px;
  }
  .content .row{
    margin: 0px;
  }
  .f_i img{
    width:21%;
    height: 21%; 
  }
  @media screen and (max-width: 767px){
  .navr ul li a {
    display: inline-block;
    width: 65px;
    height: 50px;
    text-align: center;
    line-height: 50px;
    color: #151515;
    font-size: 14px;
}
@media screen and (max-width: 767px){
.navf ul li a {
    display: inline-block;
    width: 65px;
    height: 50px;
    text-align: center;
    line-height: 50px;
    color: #151515;
    font-size: 14px;
}
</style>
<!-- 轮播 -->
 <style type="text/css">

@media screen and (max-width:767px){
   .lunbo{
        width:100%;
        height:250px !important;
        position: relative;
     }
    .content3 .name {
    font-size: 20px;
    color: #252525;
    width: 80%;
    margin-left: 20%;
    margin-bottom: 30px;
    position: relative;
    top: -5px;

  }
  .img-11{
    position: relative;
    top: 47px;
    width: 41px;
  }
}
    .lunbo{
        width:100%;
        height:300px;
        position: relative;
     }
    .arrow{
       position: absolute;
       top: 90px;
       z-index: 2;
   
       cursor: pointer;
    }
    .prev{
        left: 0;
        
    }
    .next{
        right: 0;
    }
        .container-lunbo {
                width: 260px;
                height: 255px;
                overflow: hidden;
                margin:0 auto;
                position: relative;
            }
            .container-lunbo ul{
                position: absolute;
            }
           
    .container-lunbo li{
        width:130px;
        height: 250px;
        position: relative;
        top:10px;
        left:5px;
        /*border: 1px solid #000;*/
    }
    .li-img{
      margin-bottom: 5px;
    }
      .lunbo .container-lunbo img{
          width:120px;
          height:90px;
      }


      .lunbo-ul .slide{
          float:left;
          list-style: none;

      }
      .descriptdiv{
        width: 80%;
        margin-left:10%;
          clear: both;
          height:100px;
          border: 2px solid #f1f1f1;
      }
    .content3 .ceo {
    font-size: 14px;
    color: #151515;
    width: 80%;
    margin-left: 20%;
    position: absolute;
    top: 30px;
    left: 11px;
}
  </style>
</head>
<body>
<header id="header"><?php require __DIR__.'/../enruiy/header.phtml';?></header>
<!-- banner -->
<div class="banner">
	<div id="myCarousel1" class="carousel slide">
		<?php Cms_Widget::factory('Ad')->display(Cms_Service_Api_Contents_Banner::getInstance()->getListByTypeId(100194),['need_LR'=>true,]); ?>
    </div>
   <!--  <div class="ban-left">
    	<p>为了看见未来</p>
    	<p style="margin-left:20px;">相信未来的企业</p>
    </div> -->
</div>
<!-- nav -->
<div id="nav" class="navr nav-zh">
  <div class="nav-left"><i class="glyphicon glyphicon-menu-left"></i></div>
  <ul>
    <li><a href="/enruiy/consult" class='active' style="width:230px;">Breakingpoint Consulting</a><span>|</span></li>
    <li style="display: flex;justify-content: space-between;"><a style="width: 170px;" href="/enruiy/lianx">Contact us</a><span>|</span><a href="https://www.liepin.com/zhaopin/?sfrom=click-pc_homepage-centre_searchbox-search_new&d_sfrom=search_fp&key=%E7%9D%BF%E4%BB%AA" style="width:150px;">Join us</a></li>
     <li style="display: flex;justify-content: space-between;"><span>|</span><a href="/enruiy/news" style="width: 85px;">News Room</a>
     <span>|</span><a  href="http://ibreakingpoint.huodongxing.com" style="width: 120px;">Activities & Salon</a></li>
  </ul>
  <div class="nav-right"><i class="glyphicon glyphicon-menu-right"></i></div>
</div>
<!-- content -->
<div class='content'>
	<div class="container">
		<div class="row">
			<div class="">
				<div class="content1" style="padding: 10%;">
					<p class='title' style="width:120px;">Our Story</p>
					<p class='font1' style="width: 100%;">Breakingpoint founded in 2008, as a Salesforce and SAP excellent partner, it has always been a pioneer in the sector of corporate information management. In 2016, Breakingpoint has evolved from a service provider to a market trailblazer, providing full guidance and services in relation to an organization's strategy developments, information management, and specific solutions to its existing information system issues. It learns the true demands and needs of each of its clients, aiming to reduce its costs expenses and, improve the client organization's work efficiency, improve its customer satisfaction level, and eventually help it develop new sources of competitive advantages.</p>
					<!-- <img class='f1_img' src="/ruiy/images/logof.png"> -->
					<p class="font2" style="width: 100%;">Throughout the past 10 years, Breakingpoint has provided satisfactory services for Fortunate 500 companies, major private corporates and successful newcomer companies within China, and as a result, it has been recognized as a prestigious service provided in the sector. In 2017, Breakingpoint has reached a new “breaking point” by developing innovative and digital solutions to various organizations in the retailing, automobile and residential sector, and has developed positive and sustainable business relations with all of its client companies. In the short future, Breakingpoint is committed to continuing providing services to the highest standard to meet the specific needs and requirements of its partners.</p>
					<div class='f_i'>
						<img src="/ruiy/images/zx_17.jpg" style="position: relative;top: -160px;">
						<div class='f_f f_f_1'>
							<p class='f1'>Core values</p>
							<p class='f2'>To be an ethical organization that is devoted to providing the most appropriate solutions to specific issues facing the client’s company.</p>
							<p class='f2'>To be a platform company that values the career growth of employees and interests of its partners and clients. </p>
						</div>
					</div>
					<div class='f_i'>
						<img src="/ruiy/images/zx_13.jpg" style="position: relative;top: -35px;">
						<div class='f_f f_f_2'>
							<p class='f1'>Organizational culture</p>
							<p class='f2'>Broadminded, Brave, Innovative, Reliable, Collaborative</p>
						</div>
					</div>
				</div>
				<div class="content3" style="padding: 50px;">
					<p class='title'>Our Character</p>
					<div class="font"  style="width: 100%">
						<p class="f1">Breakingpoint is not your typical IT services company. We're more partner than provider. On purpose. For us, earning your trust is just as important as earning your business. So we'll never hustle you. Instead, we'll hustle for you. 
						</p>
						<p class="f1">We don't buy hype. We believe actions speak louder than words. And results trump promises. Always. We understand ones and zeros while being mindful of X's and O's. We heart tech and hate “it can't be done.” We're not pushy. Still, we will push back when we think it’s best for you. 
						</p>
						<p class="f1">We know simple is never easy, yet strive for it relentlessly. We will never stop for it. We are Breakingpoint, your best working partner.  
						</p>
					</div>
				</div>
				<div class="content3">
					<p style='margin-bottom:10px;width:175px;' class="title">Our Leadership</p>
					<div class="t1">
						<div class="row">
							<div class="col-sm-1">
								<img class='img-11' src="/ruiy/images/zx_25.jpg">
							</div>
							<div class="col-sm-11">
								<P class="name">李子璇 <span style='color: #999;font-size: 20px;'>&nbsp;&nbsp;Tulipe Lee</span></P><p class="ceo">Founder &amp; CEO</p>
								<hr class='hr'>
								<p class='y1'><img src="/ruiy/images/d.png">Specialization <span></br>Design and implement of innovative information management systems</span>	</p>
								<p class='y1'><img src="/ruiy/images/d.png">Values & Norms <span></br>To help  our company and its partners to achieve a mutually beneficial partnership based on </span>	</p>
								<p class="cont">Lee is an experienced expert in the IT field, and an honor guest of the Development Scheme for Chinese entrepreneurs. She has a work experience of 15 years in the field of CRM and corporate information management, and has been recognized as one of the top global partners of Salesforce. She is also one of the earliest advocates of cloud computing in China, and has years of work experiences in providing specific digital solutions to the information management of traditional corporates in China. She used to be a valuable member of the Headquarters of PLA General Staff, and has worked for prestigious IT companies in China. In 2008, She founded Breakingpoint, aiming to design, develop and implement highly efficient digital solutions for companies'IT management systems. She has gained an EMBA degree in 2016 in China Europe International Business School (CEIBS).</p>
							</div>
						</div>
					</div>
					<div class="t2">
						<div class="row">
							<div class="col-sm-1">
								<img class='img-11' src="/ruiy/images/zx_28.png">
							</div>
							<div class="col-sm-11">
								<P class="name">邴喆 <span style='font-size:20px;color:#999;'>&nbsp;&nbsp;Anson Bing</span></P><p class="ceo">Co-founder</p>
								<hr class='hr'>
								
								<p class='y1'><img src="/ruiy/images/d.png">Specialization <span></br>Consultant on innovative management of corporate operations</span></p>
								<p class='y1'><img src="/ruiy/images/d.png">Values & Norms  <span></br>It is important to extend our innate knowledge, and incorporate both theoretical knowledge and work experiences in the real world to provide the most suitable and appropriate solutions for specific challenges and problems. </span>	</p>
								<p class="cont">Bing Graduated from China Europe International Business School(CEIBS) EMBA and has 21 years of work experience in the field of information management and management consulting. He used to be a valuable member of government economic management departments, IT companies, consulting organizations, and has a unique view and in-depth understanding of providing digital solutions for traditional organizations, especially in the sectors of household appliances, consumer goods retailing, automobile, with a wealth of practical experience in establishing enterprise operation management, innovation management and amoeba business system.</p>
								<ul class="ul1">Previous awards:
									<li>•  Top CIO in 2014 based on evaluations of the National Ministry of Industry and Information of China</li>
									<li>•  Top CIO in 2012 based on evaluations of the IT Value Alliance of China</li>
									<li>•  Top CIO in China in 2012 based on evaluations of the summit forum on the development of industrialization and information integration in China</li>
									<li>•  Excellent CIO in 2013 and 2014 by evaluations of the ZheJiang Enterprise Information Association</li>
								</ul>
							</div>
						</div>
					</div>
          <div class="t3">
            <div class="row">
              <div class="col-sm-1">
                <img class='img-11' src="/ruiy/images/zx_29.png">
              </div>
              <div class="col-sm-11">
                <P class="name">陈卓能 <span style='font-size:20px;color:#999;'>&nbsp;&nbsp;Neo Chen </span></P> <p class="ceo">Co-founder</p>
                <hr class='hr'>
               
                <p class='y1'><img src="/ruiy/images/d.png">Specialization 
                <span></br>Strategy planning and business transformation</span> </p>
                <p class='y1'><img src="/ruiy/images/d.png">Values & Norms  <span></br>Confidence in others' honesty is no light testimony of one's own integrity</span>  </p>
                <p class="cont">After graduation from National University of Singapore, Neo started his career as a management consultant and he has dedicated all his 15 years’ career so far in it. He worked for global management consulting firms such as IBM GBS, Accenture and Ernst & Young. His expertise lies in the fields of strategy planning and business transformation, he has very deep understanding and insight in enterprise level digital transformation and operation management. He provided services for many clients across China and Europe, especially for high-tech, telecom and auto companies.</p>
              </div>
            </div>
          </div>
				</div>
                 <?php 


                              $a=fetch_json_data('/ServerZX/GetListAll.cwg?count=1000&page=1&cms_types_id=100150')->Data;
                              //var_dump($a);

                                       
                            ?>
        <br><br>
				<div class="content3" style="margin-top:-50px;height:700px;padding: 0px">
        <br>
        <br><br>

                    <p class='title'>Our Clients</p>
                      <div class="font">
                        <div class="lunbo">
                           
                            <div class="arrow next" ><img src="/ruiy/images/right.jpg" style="width: 30px;"></div>
                             <div class="arrow prev"><img src="/ruiy/images/left.jpg" style="width: 30px;"></div>
                            <div class="container-lunbo">
                            <div class="text" style="left: 0px;" >
                                <ul class="lunbo-ul" style="position: absolute;left:0px;">
                                    <?php 
                                        $imgarr=[];
                                      foreach ($a as $key => $value) 
                                     {
                                       
                                       $imgarr[$key]=$value->_face->ico->public_src;
                                      }
                                       ?>
                                       <?php
                                       //var_dump($imgarr);
                                       $num=count($imgarr);
                                       // var_dump($num);
                                       for ($i=0; $i <$num ; $i++) { 
                                           //echo $i;
                                       $j=$i+1;


                                    ?>
                                    <li class="slide active-nav">
                                      
                                       <div class="li-img"><img src="<?php echo $imgarr[$i]; ?>"></div>

                                       <div class="li-img"><img src="<?php echo $imgarr[$j]; ?>"></div>
                                    </li>
                                    <?php  $i=$i+1;  }?>


                                   <!--  <li class="slide"><div class="li-img"><img src="/ruiy/images/li2.png"></div><div class="li-img"><img src="/ruiy/images/li2.png"></div></li>
                                                                    <li class="slide"><div class="li-img"><img src="/ruiy/images/li2.png"></div><div class="li-img"><img src="/ruiy/images/li2.png"></div></li>
                                                                    <li class="slide"><div class="li-img"><img src="/ruiy/images/li2.png"></div><div class="li-img"><img src="/ruiy/images/li2.png"></div></li>
                                                                    <li class="slide"><div class="li-img"><img src="/ruiy/images/li2.png"></div><div class="li-img"><img src="/ruiy/images/li2.png"></div></li>
                                                                    <li class="slide"><div class="li-img"><img src="/ruiy/images/li2.png"></div><div class="li-img"><img src="/ruiy/images/li2.png"></div></li> -->
                                 

                                  
                                </ul>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="descriptdiv">
                        <div class="descriptdiv-text">
                            <p class="descriptdiv-title"><?php echo $a[0]->title;?></p>
                            <div class="descript-context">
                              <span class="descriptdiv-context">
                                 <?php echo $a[0]->summary;?>
                              </span>
                            </div>
                        </div>
                    </div>
                    <!-- <div id="text" style="width: 20px;height: 20px;background: #000;left: 0px;" onclick=""></dir> -->
</div>
</div>
				<script type="text/javascript"></script>
			</div>
			<div class="" style="padding-left:0;">
			<!-- 	<div class="box">
					<p class="title"><span class="xian">|</span>关注我们</p>
					<p style='margin:15px;'>
            <a target="_blank" href="http://www.linkedin.com/groups?gid=3291404"><img src="/ruiy/images/zx_03.jpg"></a>
						<a  target="_blank" href="https://www.facebook.com/ibreakingpoint"><img src="/ruiy/images/zx_05.jpg"></a>
						
						<a id='cimg' href="javascript:;"><img src="/ruiy/images/zx_07.jpg"></a>
					</p>
					<p id='pimg' style='text-align:center;display: none;'><img style='width:80%;' src="/ruiy/images/er.jpg"></p>
				</div> -->
				<div class="box">
					<p class='title'><span class="xian">|</span>Market Collaboration</p>
					<p class='s1'>Hotline：021-34010561</p>
					<p class='s1'>Email：even.zhang@ibreaking point.com</p>
				</div>
			<!-- 	<div class="box">
					<p class='title'><span class="xian">|</span>阅读参考</p>
					<?php $b=fetch_json_data('/ServerZX/GetListAll.cwg?count=5&page=1&cms_types_id=100120')->Data; ?>
					<?php                         
                        
                          foreach ($b as $key => $value) {
                          	//var_dump($value);
                      
                      ?>
                    <a href="/news/<?php echo $value->id.'.html';?>" style='margin-right: 0px;' target="_blank">
					<p class='wei'><?php echo $value->title;?></p>
					<p class='s1 w1'><?php echo $value->summary;?></p><hr style="margin-top: 10px; margin-bottom: 10px;">
					</a>

                   <?php } ?>
				</div> -->
			</div>
		</div>
	</div>
</div>
             <?php 
                        $arr=[];
                        $summary=[];
                        foreach ($a as $key => $value) {
                           $arr[$key]=$value->title;
                           $summary[$key]=$value->summary;
                        }
                         // var_dump($arr);
                         // var_dump($summary);
                       // echo $arr[1];
                        //$ar=json_decode($arr);
                    //  $summ=json_encode($summary);
                      // var_dump($summ);
                   /* echo "var data =". $summ;
                    echo "<script>alert(data[0])</script>";*/
                  
             ?>
<!-- footer -->
 <div id='footer'><?php require __DIR__.'/../enruiy/footer.phtml';?></div>
<script type="text/javascript" src="/ruiy/js/jquery.min.js"></script>
<script type="text/javascript" src="/ruiy/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="/ruiy/js/bootstrap.js"></script>
<script type="text/javascript" src="/ruiy/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/ruiy/js/main1.js"></script>
<!-- <script type='text/javascript' src='/ruiy/js/img-change.js'></script> -->
<script type="text/javascript">
$(function(){
            
            var list = document.getElementsByClassName('lunbo-ul')[0];
            var prev = document.getElementsByClassName('prev')[0];
            var next = document.getElementsByClassName('next')[0];
            var oLi  = list.getElementsByTagName('li');
            var oTilite = document.getElementsByClassName('descriptdiv-title')[0];
            var oText = document.getElementsByClassName('descriptdiv-context')[0];
            var oImg = list.getElementsByTagName('img');
            /*var arr1 = ["博士伦1","博士伦2","博士伦3","博士伦4","博士伦5","博士伦6","博士伦7","博士伦8","博士伦9","博士伦10","博士伦11","博士伦8",];*/
           /* var arr2 = ["博士伦是一家全球性的眼睛保健公司，致力于通过创新的科技与技术，让消费者看得更好、形象更好、感觉更好。博士伦成立于1853年，目前年度营业额近二十亿美...","","博士伦是一家全球性的眼睛保健公司，致力于通过创新的科技与技术，让消费者看得更好、形象更好、感觉更好。博士伦成立于1853年，目前年度营业额近二十亿美...","","","","","","","","","","",""];*/
           /*var arr1=<?php echo json_decode($arr);?>;
           var arr2=<?php echo json_decode($summary);?>;*/
             var arr1=<?php  echo json_encode($arr);?>;
             var arr2=<?php  echo json_encode($summary);?>;
            for(var i =0;i<oImg.length;i++){
                (function(i){
                oImg[i].onmouseover = function(){
                    oTilite.innerHTML = arr1[i];
                    oText.innerHTML = arr2[i];
                   oImg[i].style.cssText = "box-shadow:0px 0px 10px #000;border-radius: 8px;";
                for(var j = 0;j<oImg.length;j++){
                    if( j != i){
                   oImg[j].style.cssText = "border:none;border-radius: 0px;";
                    }
                }
                }
                oImg[i].onmouseout = function(){
                   oImg[i].style.cssText = "box-shadow:0px 0px 10px #000;border-radius: 8px;";

                }
                })(i);

            }
            var i = 4;
            var page=1;
            var $parent = $("div.font");
             var $v_content = $("div.container-lunbo");
            var $v_show = $("ul.lunbo-ul");
            var v_width = $v_content.width();
            var len = $(".lunbo-ul img").length;
            var page_count = Math.ceil(len/i);
            $("div.next").click(function(){
                if(!$v_show.is(":animated")){
                    if(page == page_count){
                        $v_show.animate({left:'0px'},"slow");
                        page=1;
                    }else{
                        $v_show.animate({left:'-='+v_width},"slow");
                        page++;
                    }
                }
            });
            $("div.prev").click(function(){
                if(!$v_show.is(":animated")){
                    if(page==1){
                        $v_show.animate({left:'-='+v_width*(page_count-1)},"slow");
                        page=page_count;
                    }else{
                        $v_show.animate({left:'+='+v_width},"slow");
                        page--;
                    }
                }
            });
        });
</script>
<script>
$(document).ready(function(){
  var idx=0;//记录当前命中的索引
  var width=$('#nav ul').width();
  for(var i=0;i<$("#nav ul li").length;i++){
    
    $("#nav ul li").eq(i).css({
      'position':'absolute',
      'left':width*i+'px'
    })
  }
  $('#nav .nav-right').click(function(){
    if(idx<$("#nav ul li").length-1){
      $("#nav ul li").eq(idx).animate({
        position:'absolute',
        left:-width+'px'
      },300);
      $("#nav ul li").eq(idx+1).animate({
        position:'absolute',
        left:0
      },300);

      $("#nav1 ul li").eq(idx).animate({
        position:'absolute',
        left:-width+'px'
      },300);
      $("#nav1 ul li").eq(idx+1).animate({
        position:'absolute',
        left:0
      },300);
      idx++;
    }
  });
  $('#nav .nav-left').click(function(){
    if(idx>0){
      $("#nav ul li").eq(idx).animate({
        position:'absolute',
        left:width+'px'
      },300);
      $("#nav ul li").eq(idx-1).animate({
        position:'absolute',
        left:0
      },300);

      $("#nav1 ul li").eq(idx).animate({
        position:'absolute',
        left:width+'px'
      },300);
      $("#nav1 ul li").eq(idx-1).animate({
        position:'absolute',
        left:0
      },300);
      idx--;
    }
  });

  for(var i=0;i<$("#nav1 ul li").length;i++){
    
    $("#nav1 ul li").eq(i).css({
      'position':'absolute',
      'left':width*i+'px'
    })
  }
  $('#nav1 .nav-right').click(function(){
    if(idx<$("#nav1 ul li").length-1){
      console.log(idx);
      $("#nav ul li").eq(idx).animate({
        position:'absolute',
        left:-width+'px'
      },300);
      $("#nav ul li").eq(idx+1).animate({
        position:'absolute',
        left:0
      },300);

      $("#nav1 ul li").eq(idx).animate({
        position:'absolute',
        left:-width+'px'
      },300);
      $("#nav1 ul li").eq(idx+1).animate({
        position:'absolute',
        left:0
      },300);
      idx++;
    }
  });
  $('#nav1 .nav-left').click(function(){
    if(idx>0){
      $("#nav ul li").eq(idx).animate({
        position:'absolute',
        left:width+'px'
      },300);
      $("#nav ul li").eq(idx-1).animate({
        position:'absolute',
        left:0
      },300);

      $("#nav1 ul li").eq(idx).animate({
        position:'absolute',
        left:width+'px'
      },300);
      $("#nav1 ul li").eq(idx-1).animate({
        position:'absolute',
        left:0
      },300);
      idx--;
    }
  });
})
</script>
</body>
</html>