	<script type="text/javascript" src="/ruiy/js/jquery.min.js"></script>
	<script type="text/javascript" src="/ruiy/js/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/ruiy/js/bootstrap.js"></script>
    <script type="text/javascript" src="/ruiy/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/ruiy/js/main1.js"></script>
<div class="footer1">
	<li><img id='erw' style='width:150px;display: none;' src="/ruiy/images/er.jpg"></li>
					<li class='xtub'>
						<a target="_blank" href="https://www.facebook.com/ibreakingpoint"><img src="/ruiy/images/zx_03.jpg""></a>
						<a target="_blank" href="http://www.linkedin.com/groups?gid=3291404" ><img src="/ruiy/images/zx_05.jpg"></a>
						<a id='er' href="javascript:;"><img style="width:35px;" src="/ruiy/images/weixin2.png"></a>
					</li>
					<li class='yi' style='color:#fff;font-size:16px;margin-top:10px;'>Customer Inquiry：400-820-7332</li>
					<li class='yi' style='color:#fff;font-size:16px;margin-top:10px;'>Market Collaboration：021-34010561</li>
	<div class="col-sm-12 foot">&copy; 2018 ibreakingpoint.com &nbsp; Shanghai ruiyuan software information consulting co., LTD. All rights reserved for Shanghai ICP 11045576 -1.</div>
</div>
<script type="text/javascript" src='/ruiy/js/jquery-2.1.1.min.js'></script>
<script type="text/javascript">
	$('#er').click(function(){
		if($("#erw").css("display") == 'none'){
			$('#erw').css('display',"block");
		}else{
			$('#erw').css('display',"none");
		}
	})

</script>
<style type="text/css">
	.footer1{
		width: 100%;
	    background: #252525;
	    padding: 10px 0 0;
	    height: 100%;
	    text-align: center;
	    margin: 0 auto;
	}
	.footer1 li{
		list-style: none;

	}
	.footer1 li img{
		margin: 10px auto 10px;
		    border-radius: 7px;
	}
	.foot{
		background:#161616;
		padding: 10px;
		margin-top: 14px;
	}
</style>