<script type="text/javascript" src="/ruiy/js/jquery.min.js"></script>
<script type="text/javascript" src="/ruiy/js/jquery-2.1.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="/ruiy/css/iconfont.css">
<div class="header1">
			<div class="logo">
				<a id="bread" href="javascript:;"><img src="/ruiy/images/log-b.png"></a>
				<a href="/enruiy/index"><img id="logo1" src="/ruiy/images/logow2.png"></a>
			</div>
			<div class="en">	
				<a id="zhong" class="l2" href="javascript:;">中文</a>
				<span style='color: #bbbcbc;padding: 0 10px;'>|</span>
				<a id="en" class="l2" href="javascript:;">English</a>
			</div>
			<div class="right11"  style="display:none;">
				<ul>
					<li class='item_p ' >
				          <a  href="/enruiy/index/" class="item-a">Home
				          </a>
          			</li>
					<li class='item_p server1'><a href="javascript:;" class="item-a">Services&nbsp;&nbsp;&nbsp;<i class="iconfont icon-jiantouxia"></i></a>
				        <ul class='hide'>
				           	<li class='er'><a style='border-top:0;' href="/enruiy/serve/">Management Consulting</a>
					           	<ul class='er_son'>
					           		<li class='item_son_p'><a href="/enruiy/innovate/">Strategy Transformation</a></li>
					           		<li class='item_son_p'><a href="/enruiy/busi/">Business Management</a></li>
					           		<li class='item_son_p'><a href="/enruiy/itconsult/">IT Strategic Planning</a></li>
					           	</ul>
				           	</li>
				           	<li class='er' class='item_son_p'><a  href="/enruiy/softwave/">Software</a>
				           		<ul class='er_son'>
				           		    <li class='item_son_p'><a href="/enruiy/spa/">SAP</a></li>
					           		<li class='item_son_p'><a  href="/enruiy/salesforce/">Salesforce</a></li>
					           	</ul>
					        </li>	
				        </ul> 
					</li> 
					<li class='item_p hangy1'><a  href="javascript:;"  class="item-a">Industries<i class="iconfont icon-jiantouxia"></i></a>
						 <ul class='hide'>
				           	<li class='er' class='item_son_p'><a style='border-top:0;' href="/enruiy/engine/">Automobile</a>
					           	<ul class='er_son'>
					           		<li class='item_son_p'><a href="/enruiy/engine/">Automaker</a></li>
					           		<li class='item_son_p'><a href="/enruiy/dealer/">Dealers</a></li>
					           	</ul>
				           	</li>
				           	<li class='er'><a href="/enruiy/land/">Real Estate</a></li>
				           	<li class='er'><a href="/enruiy/retail/">New Retail</a></li>
				        </ul>
					</li>	
					<li class='item_p ours1'><a href="javascript:;"  class="item-a">About us<i class='iconfont icon-jiantouxia'></i></a>
						 <ul class='hide'>
				           	<li class='er'><a style='border-top:0;' href="/enruiy/consult/">Breakingpoint Consulting</a>
					        <li class='er'><a href="/enruiy/lianx/" >Contact us</a>
				           	<li class='er'><a href="https://www.liepin.com/zhaopin/?sfrom=click-pc_homepage-centre_searchbox-search_new&d_sfrom=search_fp&key=%E7%9D%BF%E4%BB%AA" target="_blank">Join Us</a></li>
				           	<li class='er'><a href="/enruiy/news/">News Room</a>
				           	<li class='er'><a href="http://ibreakingpoint.huodongxing.com " target="_blank">Activities & Salon</a></li>
				        </ul>
					
							<li class='item_p'><a  href="https://www.liepin.com/zhaopin/?sfrom=click-pc_homepage-centre_searchbox-search_new&d_sfrom=search_fp&key=%E7%9D%BF%E4%BB%AA" target="_blank" class="item-a">Join us</a></li>
					</li>
					<!-- <li class='item_p'><a  href="#">400-820-7332</a></li>
					<li class='item_p'><a  href="/ruiy/lianx">联系我们</a></li> -->
				</ul>
			</div>
			
</div>

<script type="text/javascript">
$('body').load(function(){
	$(".right11").css("display",'block');
})
$(document).ready(function(){
	$(".server1").click(function(){
		if($(".server1>ul").hasClass('show')){
			$(".header1").removeClass("header2");
			$(".server1>a").css("color",'#fff');
			$(".server1>ul").addClass('hide').removeClass('show');
			$(".server1>a>i").addClass("icon-jiantouxia").removeClass("icon-jiantoushang");
		}else{
			$(".header1").addClass("header2");
			$(".server1>ul").addClass('show').removeClass('hide');
			$(".server1>a").css("color",'#e40010');
			$(".server1>a>i").addClass("icon-jiantoushang").removeClass("icon-jiantouxia");
		}
	})
	$(".hangy1").click(function(){
		if($(".hangy1>ul").hasClass('show')){
			$(".header1").removeClass("header2");
			$(".hangy1>a").css("color",'#fff');
			$(".hangy1>ul").addClass('hide').removeClass('show');
			$(".hangy1>a>i").addClass("icon-jiantouxia").removeClass("icon-jiantoushang");
		}else{
			$(".header1").addClass("header2");
			$(".hangy1>a").css("color",'#e40010');
			$(".hangy1>ul").addClass('show').removeClass('hide');
			$(".hangy1>a>i").addClass("icon-jiantoushang").removeClass("icon-jiantouxia");
		}
	})
	$(".ours1").click(function(){
		if($(".ours1>ul").hasClass('show')){
			$(".header1").removeClass("header2");
			$(".ours1>a").css("color",'#fff');
			$(".ours1>ul").addClass('hide').removeClass('show');
			$(".ours1>a>i").addClass("icon-jiantouxia").removeClass("icon-jiantoushang");
		}else{
			$(".header1").addClass("header2");
			$(".ours1>a").css("color",'#e40010');
			$(".ours1>ul").addClass('show').removeClass('hide');
			$(".ours1>a>i").addClass("icon-jiantoushang").removeClass("icon-jiantouxia");
		}
	})
	
	$("#bread").click(function(){
		if(($(".right11").css("display")=='none') == true){
			$(".right11").css("display",'block');
		}else{
			$(".right11").css("display",'none');
		}
		
	
	})


})
window.addEventListener('scroll',function(e){
	var t = document.documentElement.scrollTop || document.body.scrollTop;
	if(t > 100){
	 	$('.header1').css({
	 		"position":"fixed",
	 		"background":"#323232"
	 	});
	 	$('#logo1').attr('src','/ruiy/images/logob2.png');
	 	$("#bread img").attr("src","/ruiy/images/logo-h.png")
	 }else{
	 	$('.header1').css({
	 		"position":"relative",
	 		"background":"#fff"
	 	});
	 	$('#logo1').attr('src','/ruiy/images/logow2.png')
	 	$("#bread img").attr("src","/ruiy/images/log-b.png")
	 }
	})
</script>



<style type="text/css">
	  [v-cloak] { 
	    display: none; 
	  } 
	#header{
	height:73px;
	background:#323232;
	}
	
	.header1{
		height:75px;
		width:100%;
		position: relative;
		z-index: 1000;
		background: #fff;
	}
	.logo img{
		width: 220px;
    	margin-top: 10px;
	}
	.logo{
		width:100%;
		margin: 0 auto;
		text-align: center;
	}
	.right11{
		width: 100%;
	    background: #3d3d3d;
	    top: -20px;
	    right: 0;
	    position: relative;
	    color: #fff;
	    text-align: left;
	    font-size: 0.32rem;
	    z-index: 10;
	    overflow-y: auto;
	    display: none;
	    transition: all .3s linear;
	}
	.header2{
		/*position: relative !important;*/
	}
	.right11 ul{
		margin-bottom: 0;
	}
	.right11 .er > a{
		border-top: 1px solid #444;
		padding: 10px 5px 0 30px !important;
   	    height: 64px !important;
	}
	.item_p a{
		padding: 0px 5px 0px 10px;
		font-size:20px;
		color: #fff;

	}
	.item_p>a{
		color: #fff;
		height: 44px;
		line-height:44px;
		font-size:16px;
		display: block;
		border-top: 1px solid #f1f1f1;
	}
	.item_p .er a{
		padding: 0px 5px 0px 30px;
		font-size:20px;
		color: #fff;
	}
	.item_p .er a{
		height:44px;
		line-height: 44px;
		display: block;
		background:#000;
	}

	.item_p .er_son a{
		padding: 0px 5px 0px 30px;
		font-size:14px;
		color: #ccc;
	}
	.hide{
		display: none;
		transition: all 0.2s;
        -webkit-transition: all 0.2s;
	}
	.show{
		height:100% !important;
		transition: all 0.2s;
        -webkit-transition: all 0.2s;
        border-top: 2px solid #e40010;
        margin-bottom: 10px;
        background: #000;
	}
	.item_p a:hover,
	.item_p a:active{
		text-decoration: none;
	}
	.right11 .er .er_son{
		margin-bottom: 10px;
	}
	#bread img{
		display: block;
	    position: relative;
	    left: 14px;
	    top: 4px;
	    width: 38px !important;
	    float: left;
	    border-radius: 50%;
	}
	.iconfont{
		float: right;
    	margin-right: 20px;
	}
	i{
		transition: all 0.2s;
	    -webkit-transition: all 0.2s;
	}
	.en{
		width: 100%;
	    padding: 5px 19px;
	    background: #393939;
	    border-top: 1px solid #555;
	    text-align: right;
	    position: relative;
    	top: 11px;
	}
	.en a{color: #bbbcbc;}
@media screen and (max-width: 767px){
	.navf {
	    position: fixed;
	    top: 95px !important;
	    text-align: center;
	    background: #e9e9e9;
	    z-index: 10;
	    width: 100%;
	}
	.carousel-control{
		display: none !important;
	}
}
</style>

