	<!DOCTYPE html>
	<html>
	<head>
		<title></title>
		<style type="text/css">
			.box .lix a{
				display: block;
			    width: 170px;
			    text-align: center;
			    background: #c7161e;
			    line-height: 30px;
			    color: #fff;
			    margin: 0 auto;
			    border-radius: 2px;
			}
			.lix a:hover{
				background: #ee1818;
			}
			.box{
				margin-top: 20px;
			}
			body .content .row .innovate,
body .content .container .box{
	width: 100%;

}
		</style>
	</head>
	<body>
	<div class="right">
				<div class="box">
					<p class="title"><span class="xian">|</span>联系我们</p>
					<p class='lix'><a href="/ruiy/lianx/">通过网上表格联系我们</a></p>
				</div>
				<div class="box">
					<p class="title"><span class="xian">|</span>关注我们</p>
					<p style='margin:15px;'>
						<a target="_blank" href="https://www.facebook.com/ibreakingpoint"><img src="/ruiy/images/zx_03.jpg"></a>
						<a target="_blank" href="http://www.linkedin.com/groups?gid=3291404"><img src="/ruiy/images/zx_05.jpg"></a>
						<a id='cimg' href="javascript:;"><img src="/ruiy/images/zx_07.jpg"></a>
					</p>
					<p id='pimg' style='text-align:center;display: none;'><img style='width:80%;' src="/ruiy/images/er.jpg"></p>
				</div>
				<div class="box">
					<p class='title'><span class="xian">|</span>阅读参考</p>
					

               <?php $b=fetch_json_data('/ServerZX/GetListAll.cwg?count=5&page=1&cms_types_id=100121')->Data; ?>
					<?php                         
                        
                          foreach ($b as $key => $value) {
                          	//var_dump($value);
                      
                      ?>
                    <a href="/news/<?php echo $value->id.'.html';?>" style='margin-right: 0px;' target="_blank">
					<p class='wei'><?php echo $value->title;?></p>
					<p class='s1 w1'><?php echo $value->summary;?></p>
					</a>

                   <?php } ?>
                     

					<!-- <p class='wei'>. 微信文章标题</p>
					<p class='s1 w1'>微信文章介绍简介微信微信文章介绍</p>
					<p class='s1 w1'>简介微信文章介绍简介</p> -->
				</div>
	</div>
	</body>
	</html>